jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        frontend:
            pattern:            .*
            anonymous:          true
            logout:             true
            form_login:
                provider:       fos_userbundle
                login_path:     /login/
                check_path:     /login_check
                use_forward:    false
                failure_path:   null
            remember_me:
                key:            %remember_me.secret%
                user_providers: fos_userbundle
                name:           theododrinksauth
                remember_me_parameter: _remember_me
                lifetime:       31104000 # 1 year
            oauth:
                resource_owners:
                    google:     /login/check-google
                login_path:     /login/
                failure_path:   /login/
                oauth_user_provider:
                    service:    hwi_oauth.user.provider.fosub_bridge

    access_control:
        # The WDT has to be allowed to anonymous users to avoid requiring the login with the AJAX request
        - { path: ^/_wdt/,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # AsseticBundle paths used when using the controller for assets
        - { path: ^/js/,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login/,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/,     roles: ROLE_ADMIN }
        - { path: ^/,           roles: ROLE_USER }
